workflows:
  testFlight:
    name: hassous
    environment:
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - Provisioning_walpaper
        certificates:
          - CertificateM
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hassousalmonim@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: 3LNX877CUW
        key_id: 3LNX877CUW
        issuer_id: f4abfcab-d9ef-4d08-bbbd-55cb291f239a
        submit_to_testflight: true
